# Generated by Django 3.1.4 on 2021-01-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registerdata',
            table='register',
        ),
    ]
