# Generated by Django 3.1.4 on 2021-02-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='register_user.registerdata'),
        ),
    ]
