# Generated by Django 3.1.4 on 2021-04-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0004_auto_20210216_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='email',
            new_name='user',
        ),
    ]
